### ISSUE TITLE
CMake, build shared libraries not implemented

### ISSUE THREAD

**Issue by aleixtejadagimenez** [wavelet-lab/usdr-lib#40]
Top CMakeLists. txt variable 'BUILD_SHARED_LIBS' is not referenced anywhere. Perhaps that should be an option() that later on toggles the build of libusdr and libusdr-dsp from SHARED to STATIC.

**Comment by vd2org** [comment]
Fixed. 

Now you can choose static build by -DBUILD_SHARED_LIBS=OFF.
However, the soapy plugin will be shared anyway.

Happy hacking!
